### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by rklak** [MobProgramming/MobTimer.Python#12]
Any chance on Linux/Ubuntu support?

**Comment by DeadlyApps** [comment]
If you download the source code. I believe MobTimer.py will run the timer. I will eventually look into a stand alone download.

**Comment by gregorriegler** [comment]
Running MobTimer.py on linux doesn't quite work out for me.
First I have a problem with `pypiwin32` in requirements.txt which I have to remove.
Then I had to install `tkinter` via apt.
Now I get the following error:
```
$ python3 MobTimer.py
Traceback (most recent call last):
  File "MobTimer.py", line 3, in <module>
    root = MobTimerController()
  File "/home/mob/MobTimer.Python/Frames/MobTimerController.py", line 49, in __init__
    self.iconbitmap(default='time-bomb.ico')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2078, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, '-default', default)
_tkinter.TclError: wrong # args: should be "wm iconbitmap window ?bitmap?"
```

Linux support would be awesome. Would like to use it for this: https://github.com/gregorriegler/remdev-azure

**Comment by DeadlyApps** [comment]
Hey, unfortunately I do not have time to work on a fix myself but I would be happy to review and accept a pull request. Bitmap errors are probably related to PIL and Pillow (the windows version) 

I think this may help. If you get the PIL library working for Linux then TKinter should work with it. I am not 100% sure though.
https://www.geeksforgeeks.org/how-to-install-pil-on-linux/
